In [17]:
import pandas as pd
# import numpy as np
s=pd.Series([1,4,5,2,6,3])
print(s)

0    1
1    4
2    5
3    2
4    6
5    3
dtype: int64

In [14]:
import numpy as np

arr=np.array([[1,1,1,1],[2,2,2,2]])

arr1=[[1,1,1,1],[2,2,2,2]]
print(arr1)
print(arr[1][2])
print(arr1[1][2])
arr

[[1, 1, 1, 1], [2, 2, 2, 2]]
2
2

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [28]:
# s = pd.Series({'a': 1, 'b': 2, 'c': 3})
print(s[0])

1

C:\Users\Madhav Naga Sri Ram\AppData\Local\Temp\ipykernel_10100\1576197440.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [25]:
rd=pd.read_excel("MCCS - 2_Vth sem.xlsx")
# rd.pd.dataframe
# df=pd.DataFrame(rd)
# df.tail(10)
rd

,"ADIKAVI NANNAYA UNIVERSITY, RAJAHMUNDRY\t",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,B.SC DEGREE EXAMINATIONS JAN - 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"ADITYA DEGREE COLLEGE, KAKINADA . CODE NO. 037",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VSEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,MCCS - 2,NaN,NaN,NaN
3,S. NO,R. NO,REGD NO,NAME OF THE STUDENT,SL,MAT\nV A,MAT\nV A Points,MAT\nV B,MAT\nV B Points,CHEM\nV A,...,CHEM\nV B Points,CS\nV A,CS\nV A Points,CS\nV B,CS\nV B Points,Tentative CGPA,RESULT,NaN,NaN,NaN
4,1,25,210377146329,ANISETTI RAM SUDHEER REDDY,Telugu,C,5,B+,7,B+,...,5,B,6,C,5,5.83,PASS,NaN,NaN,NaN
5,2,1,210377146336,BAVISETTI ABHINAYA,Telugu,C,5,B,6,D,...,6,A,8,A,8,6.17,PASS,NaN,NaN,NaN
6,3,30,210377146344,DOOLLA DHANA LAKSHMI,Telugu,F,0,F,0,C,...,0,D,4,B,6,FAIL,FAIL,NaN,Grade,Points
7,4,4,210377146345,GEDALA PADMAJA,Telugu,B+,7,B+,7,B+,...,9,A,8,A,8,7.67,PASS,NaN,O,10
8,5,21,210377146348,GOLLU DEVA DURGA PRASANNA NAIDU,Telugu,B,6,F,0,B+,...,9,B+,7,A,8,FAIL,FAIL,NaN,A+,9
9,6,31,210377146350,GUNDRA SAI RAM BABU,Hindi,B,6,D,4,C,...,7,B+,7,B,6,5.83,PASS,NaN,A,8
10,7,18,210377146351,GURUGUBELLI SAIKIRAN,Hindi,C,5,F,0,B,...,8,B+,7,D,4,FAIL,FAIL,NaN,B+,7
11,8,7,210377146352,ILLA GREESHMA SATYA SRI,Telugu,B,6,C,5,B,...,6,B+,7,B,6,6,PASS,NaN,B,6
12,9,35,210377146353,KAKARAPALLI MOHAN KUMAR,Hindi,C,5,D,4,B,...,6,B+,7,B,6,5.67,PASS,NaN,C,5
13,10,40,210377146355,KANNAVARAPU SAI,Telugu,F,0,D,4,C,...,5,C,5,F,0,FAIL,FAIL,NaN,D,4
14,11,24,210377146359,KEERTHI VENKATA MANIKANTA,Telugu,F,0,F,0,C,...,4,B+,7,C,5,FAIL,FAIL,NaN,F,0
15,12,22,210377146365,KOYYA SRINU,Telugu,B+,7,D,4,C,...,9,B+,7,B,6,6.33,PASS,NaN,NaN,NaN
16,13,6,210377146367,KURAMDASU DURGA NAGA DEVI,Telugu,B,6,B+,7,A,...,9,A,8,A+,9,7.83,PASS,NaN,NaN,NaN
17,14,23,210377146368,MAKIREDDY GEETHU SAI SAMPATH KUMAR,Telugu,D,4,F,0,D,...,7,B+,7,C,5,FAIL,FAIL,NaN,NaN,NaN
18,15,39,210377146369,MALLIDI HEMANTH REDDY,Telugu,B+,7,F,0,B,...,8,B,6,A,8,FAIL,FAIL,NaN,NaN,NaN
19,16,37,210377146372,MOHAMMAD SAJID,Hindi,B+,7,D,4,C,...,5,B,6,D,4,5.17,PASS,NaN,NaN,NaN
20,17,10,210377146377,NALAMATI SAI DIVYA,Telugu,C,5,B,6,A,...,9,A+,9,A,8,7.5,PASS,NaN,NaN,NaN
21,18,34,210377146378,NALLA VENKATA TRINADH,Telugu,C,5,F,0,B,...,8,C,5,C,5,FAIL,FAIL,NaN,NaN,NaN
22,19,11,210377146381,NUNNA SIRI ADITYA,Telugu,A+,9,C,5,B,...,9,A,8,A,8,7.5,PASS,NaN,NaN,NaN
23,20,12,210377146383,PEDAKAPU SAI BABU,Telugu,D,4,B,6,B,...,6,A,8,A,8,6.33,PASS,NaN,NaN,NaN
24,21,19,210377146384,PENDRA HARINDRA,Telugu,F,0,F,0,B,...,0,C,5,F,0,FAIL,FAIL,NaN,NaN,NaN
25,22,5,210377146387,PITTA JHANSI,Telugu,C,5,B+,7,B+,...,7,C,5,B,6,6.17,PASS,NaN,NaN,NaN
26,23,8,210377146390,REKADI BALA TRIPURA SUNDARI,Telugu,C,5,A+,9,A,...,9,B+,7,A,8,7.67,PASS,NaN,NaN,NaN
27,24,3,210377146393,SUNDARANEEDI SUMANASRI,Telugu,F,0,F,0,C,...,5,F,0,F,0,FAIL,FAIL,NaN,NaN,NaN
28,25,26,210377146396,THORATI MANIKANTA VARMA,Telugu,D,4,D,4,C,...,4,D,4,D,4,4.17,PASS,NaN,NaN,NaN
29,26,38,210377146397,TUMMALAPALLI VENKATA ROHITH,Telugu,B+,7,C,5,B+,...,7,B,6,B+,7,6.5,PASS,NaN,NaN,NaN
30,27,9,210377146398,TUTTA TEJASWI,Hindi,D,4,C,5,B,...,8,B+,7,C,5,5.83,PASS,NaN,NaN,NaN
31,28,20,210377146399,VAIBOGULA TIRUMALESH,Telugu,C,5,C,5,A,...,7,B+,7,C,5,6.17,PASS,NaN,NaN,NaN
32,29,15,210377146403,VITHANALA SAI KIRAN,Telugu,C,5,C,5,B+,...,7,D,4,D,4,5.33,PASS,NaN,NaN,NaN
33,30,36,210377146404,YALLA VENKATESH,Telugu,D,4,F,0,A,...,8,B+,7,D,4,FAIL,FAIL,NaN,NaN,NaN
34,31,33,210377146405,YARRAMSETTI SATYA SANKAR RAM VASANTH,Hindi,F,0,F,0,B+,...,5,B+,7,C,5,FAIL,FAIL,NaN,NaN,NaN
35,32,13,210377146406,YELUGUBANTI SARATKUMAR,Telugu,F,0,F,0,C,...,4,C,5,B+,7,FAIL,FAIL,NaN,NaN,NaN
36,33,28,210787146079,NAGALLA MURALI SRINU,Hindi,A,8,B,6,F,...,8,A,8,B,6,FAIL,FAIL,NaN,NaN,NaN
37,34,16,210787146080,PABBINEEDI SIVA NAGENDRA,Telugu,F,0,F,0,D,...,5,C,5,F,0,FAIL,FAIL,NaN,NaN,NaN
38,35,41,210787146081,PAMPANABOYINA JOHN SATVIK,Telugu,A,8,B+,7,F,...,8,B+,7,C,5,FAIL,FAIL,NaN,NaN,NaN
39,36,2,210787146082,PENAGANTI SUJATHA,Telugu,C,5,C,5,B+,...,8,B+,7,B,6,6.33,PASS,NaN,NaN,NaN
40,37,29,210787146083,RAJANA BHASKAR,Telugu,D,4,C,5,A,...,10,B+,7,B+,7,6.83,PASS,NaN,NaN,NaN
41,38,27,210787146084,THALISETTI SURYANARAYANA,Telugu,F,0,F,0,C,...,7,B+,7,B,6,FAIL,FAIL,NaN,NaN,NaN
42,39,17,210787146085,VANTAPATI RAJESH KUMAR,Telugu,F,0,F,0,D,...,0,C,5,F,0,FAIL,FAIL,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,MAT\nV A,NaN,MAT\nV B,NaN,CHEM\nV A,...,NaN,CS\nV A,NaN,CS\nV B,NaN,NaN,RESULT,NaN,NaN,NaN
45,TOTAL NO.OF STUDENTS APPEARED,NaN,NaN,NaN,NaN,39,NaN,39,NaN,39,...,NaN,39,NaN,39,NaN,NaN,39,NaN,NaN,NaN
46,TOTAL NO.OF STUDENTS PASSED,NaN,NaN,NaN,NaN,29,NaN,24,NaN,37,...,NaN,38,NaN,34,NaN,NaN,21,NaN,NaN,NaN
47,TOTAL NO. OF STUDENTS FAILED,NaN,NaN,NaN,NaN,10,NaN,15,NaN,2,...,NaN,1,NaN,5,NaN,NaN,18,NaN,NaN,NaN
48,PASS %,NaN,NaN,NaN,NaN,74.358974,NaN,61.538462,NaN,94.871795,...,NaN,97.435897,NaN,87.179487,NaN,6.33,53.846154,NaN,NaN,NaN
49,OVERALL PASS %,NaN,NaN,NaN,NaN,0.538462,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
def myname():
    return "hello"
myname()

'hello'